### ISSUE TITLE
Update-Database error

### ISSUE THREAD

**Issue by JustCallMeAD** [sarathlalsaseendran/DotnetDeskCore3#1]
Looks like a great project but there is an issue when trying to create the database.

`Update-Database : The term 'Update-Database' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.`

**Comment by sarathlalsaseendran** [comment]
HI @JustCallMeAD , Please add "Microsoft.EntityFrameworkCore.Tools" library to project and run the EF Migration again. It is required package for all Migration. I have now added to project now. You can pull the project again or add the library manually to perform DB migration. I am closing this issue. 

Please give your feedback / queries if you face any further issues. Thanks for checking the application.
